# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
app_icon "./richtexture/Assets.xcassets/AppIcon.appiconset/hero-1024-1024x1024.png"