# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(
      workspace: "RichTexture.xcworkspace",
      scheme: "RichTexture",
      include_bitcode: true,
      #automatic_release: false, 
      #phased_release: false
      )
    upload_to_app_store
  end
  lane :icons do
    appicon(
      appicon_image_file: 'readme-resources/hero-1024.png',
      appicon_devices: [:ipad, :iphone, :ios_marketing],
      appicon_path: 'richtexture/Assets.xcassets' # output path
      )
  end
end
